feat: ERC20 Metadata connector
aurora-is-near/rainbow-token-connector pull request #71
Opened 2021-07-29 19:52 UTC by 0x3bfc

- [ ] ERC20MetadataLogger on Ethereum side
- [ ] Update NEP-141 metadata on the NEAR side
- [ ] Update ERC20 metadata on Aurora side

2021-08-18 01:32 UTC, sept-en requested changes
It'd be super nice to have this connector, thanks for adding this @0x3bfc !
At the first sight this LGTM!

2021-08-18 01:32 UTC, sept-en commented on bridge-token-factory/src/lib.rs
> +    );
Need to add `icon: Option<String>,` field there for [NEP-148](https://nomicon.io/Standards/FungibleToken/Metadata.html) compliance

2021-08-18 01:32 UTC, sept-en commented on bridge-token-factory/src/lib.rs
>  }
As the metadata could be updated either by calling either `set_metadata` directly or by verifying the proof from the `MetadataConnector`, I suggest renaming the method to something like:  `finish_updating_metadata_with_proof` to be explicit on its purpose and to eliminate possible misleading.

2021-08-18 01:32 UTC, sept-en commented on bridge-token/src/lib.rs
>      }
Add `icon` field here and in the function signature.

2021-08-18 01:32 UTC, sept-en commented on bridge-token-factory/src/lib.rs
> +            decimals.into(),
Why do you overwrite token's `reference` and `reference_hash` with empty data? As these fields don't exist in the `MetadataConnector`'s `Log`, just set those to `None` so they won't be updated in `set_metadata()` method.

2021-08-18 01:32 UTC, sept-en commented on bridge-token-factory/src/lib.rs
> +        env::log(format!("Finish updating metadata. Name:{} Symbol:{:?} Decimals:{:?} at : {:?}", name, symbol, decimals, timestamp).as_bytes());
It's not clear what's `at` for without checking the sources, so either convert the timestamp to Human date or add the suffix telling that this is indeed a timestamp. IMO the second option is preferable as it doesn't require any additional computation.

2021-08-18 01:32 UTC, sept-en commented on bridge-token/src/lib.rs
> +        {
```suggestion
        if env::predecessor_account_id() == self.controller 
            || env::predecessor_account_id() == env::current_account_id() {
```

The indentation and stylistic are wrong.

2021-09-16 07:29 UTC, mfornet approved these changes

2021-09-16 07:29 UTC, merged