check the proof by Tx height
aurora-is-near/rainbow-token-connector pull request #82
Opened 2021-12-06 12:16 UTC by idirall22

- Check if the proof is not from an ancient block. The check is done using by comparing the Tx finality height and the minBlockAcceptanceHeight.

2021-12-08 16:14 UTC, mfornet approved these changes
LGTM.

2022-03-10 21:18 UTC, sept-en requested changes

2022-03-10 21:18 UTC, sept-en commented on erc20-connector/test/TokenLocker.js
> +    it.only('can not unlock, proof is invalid', async function () {
```suggestion
    it.only('can not unlock, proof is from the ancient block', async function () {
```

2022-03-10 21:18 UTC, sept-en commented on erc20-connector/test/TokenLocker.js
> +            )
```suggestion
        );
```

2022-03-10 21:18 UTC, sept-en commented on erc20-connector/test/TokenLocker.js
> +    it.only('can not unlock, proof is invalid', async function () {
to be fixed in a follow-up PR.

2022-03-10 21:18 UTC, sept-en commented on erc20-connector/test/TokenLocker.js
> +            )
to be fixed in a follow-up PR.

2022-03-10 21:18 UTC, sept-en approved these changes

2022-03-10 21:27 UTC, sept-en commented
Due to the lack of access to the source branch, merge conflicts will be resolved and thus merged to `maser` in the following-up PR.

2022-03-10 21:27 UTC, closed without merging